### ISSUE TITLE
Redis Connector

### ISSUE THREAD

**Issue by rchari-ml** [camunda-community-hub/camunda-8-connectors#61]
Hello, Team!

I am Raghavendra Chari from Make Labs (India). I am happy to introduce the Redis connector and think it will contribute to the community.

## About the Connector
Redis connector allows performing CRUD operations viz., get, put and delete. It handles JSON data as the message format. 
Example: Key as string and Value as any valid JSON.

## Checklist

- [Yes ] I have added a license file (and terms of use where applicable): 
https://github.com/rchari-ml/redis-connector-nodejs/blob/main/LICENSE

- [Yes ] The Readme file contains summary: 
https://github.com/rchari-ml/redis-connector-nodejs/blob/main/README.md#redis-connector-nodejs

- [Yes ] Documentation describes how to use the connector: 
https://github.com/rchari-ml/redis-connector-nodejs/blob/main/README.md

- [Yes ] Documentation describes how to install the connector: 
https://github.com/rchari-ml/redis-connector-nodejs/tree/main?tab=readme-ov-file#how-to-run-redis-connector-using-docker

- [Yes ] Documentation describes how to contact maintainer: 
https://github.com/rchari-ml/redis-connector-nodejs/tree/main?tab=readme-ov-file#contact-me

Thank you!

**Comment by xomiamoore** [comment]
Hey @rchari-ml! Thank you for submitting this connector! 🚀 

I apologize for the delay -- we are in the process of transitioning Connector listings to the Marketplace, where I see [this Connector is already listed](https://marketplace.camunda.com/en-US/apps/427600/redis-connector)! Since we are no longer compiling them in this repo, I will close this issue and make sure to update the repo so this is more clear. 

Let me know if you have any other questions!
